### PR TITLE
Fix the images in README

### PR DESCRIPTION
**Pull request by zhangtbj**
# Changes

The images cannot be shown in README.md correctly. Fix the path.

### CODE REVIEW

**Comment by zhangtbj** [comment]
Hi @rhuss ,

Thanks for helping me to setup this repo! :)

A quick question, I would like to provide some PRs to imporve this plugin.

But I found I cannot apporve or merge this PR and other team members cannot review it.

Do you know how to continue the work in this repo?

Thanks!

**Comment by rhuss** [comment]
@zhanggbj @zhangtbj (such similar github names, looks like that you are twins :) - We are currently setting up the review workflow, switching to a new way that uses GitHub CODEOWNERS (see ~/.github/CODEOWNERS). Please let me know who should be able to approve PRs in this repo, I will add them to the file.

In the meantime feel free to work on this repo, I think we should be set up soon for trying out the new review workflow.

**Comment by rhuss** [comment]
btw, I just copied over the code from client-contrib. I hope this is ok.

**Comment by zhangtbj** [comment]
Thanks @rhuss :) !

Can you please add Grace (@zhanggbj ) as the reviewer in this repo first? I will co-work with Grace to setup and enhance this plugin first.

That is fine and thank you for helping migrate the repo to here. Yes, for sure, we will keep improving this plugin.

Thanks!

**Comment by zhanggbj** [comment]
@rhuss (we do have the exact same First Name:-D)
Thank you for taking care of these!

**Review by maximilien — APPROVED** [review]
/lgtm

**Comment by zhangtbj** [comment]
Thanks Dr. Max! :)

**Pull request merged**
